### ISSUE TITLE
Exposal of `chainComponents`

### ISSUE THREAD

**Issue by edygar** [jamesplease/react-composer#47]
Could `chainComponents` be exported separately? Components with render props are really tedious to chain but there's no need to mount a Component so I can chain them.

Also, wouldn't it be `chainElements`? Just because when you say Component, you are talking about the descriptor where the element is the description. Once this function will act only with elements, saying components is wrong by definition.

**Comment by jamesplease** [comment]
Hi @edygar ! Thanks for the issue.

> Could chainComponents be exported separately? Components with render props are really tedious to chain but there's no need to mount a Component so I can chain them.

`chainComponents` no longer exists in the refactor that we plan to publish in a few days. For more, see #39 . If you'd like that functionality as a function, then maybe it makes sense to make a standalone lib for it? What do you think?

> Also, wouldn't it be chainElements? Just because when you say Component, you are talking about the descriptor where the element is the description. Once this function will act only with elements, saying components is wrong by definition.

There is a conversation about the naming over in #34 . It's not specifically about `chainComponents`, but it is about the `components` prop itself. I like that the internal API name reflects the prop name for the sake of consistency, although there is no question that the usage of the word "components" here is not the most accurate 🙂

**Comment by erikthedeveloper** [comment]
I have to ask, what is your motivation/use case for wanting this @edygar? Is it simply an alternative API you are after or are you somehow experiencing performance problems?

I will say that `chainComponents` was essentially extracted and renamed to `renderRecursive` in #39. That leaves nothing more than an invocation of it in `Component`'s render.

https://github.com/jamesplease/react-composer/blob/a77449db49ed238d5c97526a1e803c8094514c1d/src/index.js#L4-L6

In theory, it could be used within a render method, as-is, such as :arrow_down:... but I'm not convinced that we should expose internals like that or enable alternative APIs.

```diff
-<Composer components={components} children={children} />
+renderRecursive(components, [], children)
```

`react-composer` intentionally has very small API surface area (accepting only two props, `components` and `children`, as of #39) See [updated docs: API section](https://github.com/jamesplease/react-composer/tree/a77449db49ed238d5c97526a1e803c8094514c1d#api) so I feel like it wouldn't make sense to add support for alternative APIs/usages @jamesplease.

---

:memo: This is not something that I would encourage or mention in the docs... but due to `Composer` being a function component, you could invoke it as a function with props and achieve the same result as if you had imported/invoked `renderRecursive` directly:

```js
// All 3 are roughly equivalent. Untested of course! :)
<Composer components={components} children={children} />
renderRecursive(components, [], children)
Composer({components, children})
```

**Comment by jamesplease** [comment]
I am going to close this for now, because I don't think that there are actionable items here. @edygar if you think that there is, **just let us know** and we can definitely reopen this issue!

Thanks :v:

**Comment by edygar** [comment]
Sorry for such a delay to respond.

First of all, I was experimenting a lot with the approaches to make render props more readable. You can take a look at the result: https://codesandbox.io/s/q3zo18z1v6

And no, It wasn't performance, I was only asking so I wouldn't have to copy and paste it (line 40 of compose.js file). As a result, I've opted for the generator version, I've considered the code cleaner than alternatives…

Anyway, great job here ;)
